### ISSUE TITLE
History support for pat-inject

### ISSUE THREAD

**Issue by mattss** [ploneintranet/ploneintranet.theme#120]
I propose an option for pat-inject that will push the remote URL into the browser history (history.pushState) after injecting the content.

This option should be *disabled* by default as it will not always be appropriate.

history.pushState is currently supported in IE10+  (see: http://caniuse.com/#search=history.pushState)

**Comment by mattss** [comment]
@jcbrand @adrianwhite Any thoughts?

**Comment by adrianwhite** [comment]
:thought_balloon: "I'm hungry"

**Comment by jcbrand** [comment]
@mattss +1

**Comment by adrianwhite** [comment]
@mattss +1

**Comment by mattss** [comment]
Yeah so after taking a look at patternslib to see how this might be done I realised it already exists in pat-inject! Simply add 'history: record' to data-pat-inject.

More info: http://patternslib.com/demo/inject/index.html

/cc @cornae

**Comment by pilz** [comment]
It might be worth a check though. We did that for Star and abandoned it at a not necessarily complete state when it became clear that we can't support IE8. So there may be rough edges!

**Comment by mattss** [comment]
Just tried it out and it works just fine in FF and Chrome. Are we targetting IE <10 for PI? If so, there are a variety of polyfills around.

**Comment by gyst** [comment]
Current scope is IE10+. Extended backward compatibility later on (paid) demand.

--
   Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

   s o c i a l   k n o w l e d g e   t e c h n o l o g y

**Comment by mattss** [comment]
I think @cornae has now added this to the theme. Closing.
