### ISSUE TITLE
Implement an 'attachment' tooltip which initially contains Search/Browse/Upload

### ISSUE THREAD

**Issue by bfackland** [ploneintranet/ploneintranet.theme#13]
- [ ] Implement an 'attachment' tooltip
- [ ] Click paperclip to reveal attachment tooltip
- [ ] Click 'Upload' in attachment tooltip should open local computer 'Browse' dialog (a la current implementation)

..then we'll agree the MVP for Search and Browse.

**Comment by fulv** [comment]
@cornae, I believe this is implemented and can be closed.  Agreed?

**Comment by cornae** [comment]
MVP is complete indeed.
