### ISSUE TITLE
Change list of users and tags to inject (as feedback from adding mentions etc) to arrays

### ISSUE THREAD

**Issue by adrianwhite** [ploneintranet/ploneintranet.theme#15]

**Comment by fulv** [comment]
@adrianwhite This is a very old issue.  Please update it with current status, or close.

**Comment by adrianwhite** [comment]
I'll leave this one open as it might be nice to tidy up this template. It is an ugly implementation at the moment. If it don't get to it in the next two weeks I'll probably just close it as it works. :)

**Comment by fulv** [comment]
This is being sprinted on and is needed by Manuel.
