### ISSUE TITLE
Need to create way for targeting tooltip injection areas uniquely

### ISSUE THREAD

**Issue by adrianwhite** [ploneintranet/ploneintranet.theme#16]
If you interact with one tooltip area that will update it's own #items area
If you interact with another tooltip it will update the first tooltips #items area
This is because the pat-injections are all targeting #items and finding the first

**Comment by adrianwhite** [comment]
This will be resolved with #69 as all tooltip areas require unique ids to resolve #38

**Comment by adrianwhite** [comment]
Note to self: As #69 has been closed this now needs investigating independently.

**Comment by adrianwhite** [comment]
will be fixed with merge of #85

**Comment by fulv** [comment]
@adrianwhite   #85/#95 are closed/merged, so this should be complete, right?

**Comment by adrianwhite** [comment]
Yes, I thought waffle would have closed this issue as the pull request and issue were linked in waffle.
