### ISSUE TITLE
Document "day in the life of" scenarios

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet.theme#2]
Transcript the first part of the audio recording of the scenario outlined by Guido at Gatwick (in Google Drive).

Turn this into a one-page or two-page narrative writeup document in the Google Drive folder.

Do the same for the user epics we documented in April (See Google Drive)

Result: 3 or 4 one-page documents providing narrative user scenarios. Save in Google Drive

**Comment by fulv** [comment]
@gyst, is this still actionable?

**Comment by adrianwhite** [comment]
Ah, as you may be able to tell this one got forgotten about.
I did make a start but it was nothing compared to the one that @pilz did.
