### ISSUE TITLE
Need a limit on the number of lines to display on a post or comment upon initial display

### ISSUE THREAD

**Issue by adrianwhite** [ploneintranet/ploneintranet.theme#33]
Posts and comments can be extremely long, cluttering up the UI and giving a poorer UX

**Comment by fulv** [comment]
@adrianwhite, This is a very old issue.  Please update it with current status, or close.

**Comment by adrianwhite** [comment]
Closing. Can be raised by @gyst or @cornae if it becomes part of a later iteration.
