### ISSUE TITLE
Messagig pop-up does not work properly

### ISSUE THREAD

**Issue by bogdangi** [ploneintranet/ploneintranet.theme#35]
When user try to add message via messaging pop-up it does not work on network view because isolation problem.
Network page has also the same id to send message and the same ids to mention users and tags.

**Comment by fulv** [comment]
@bogdangi, what is "network view"?
please update this issue, and confirm whether it still reproduces.  otherwise, close it.
@adrianwhite, please feel free to do so, too.

**Comment by gyst** [comment]
"Network view" is a view in plonesocial which is not yet designed for ploneintranet. Closing since we first need a page design, and the current backend page is unsupported in the design.
