### ISSUE TITLE
Manage social posting wireframing progress

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet.theme#4]
Social sharing widget, including:
- mentions incl. livesearch and avatar preview
- visibility
- tags incl. autocomplete and suggestions
- files+URLs+references input incl. drag-n-drop, livesearch and tree browser
- files+URLs+references preview

Deliverable: a good and coherent set of wireframed interactions suitable to feed into the next stage of high-fidelity mockup creation.

**Comment by fulv** [comment]
@gyst, can this be closed now?

**Comment by cornae** [comment]
I guess it can be closed.
