### ISSUE TITLE
Missing the select box for the workflow inside the new post box

### ISSUE THREAD

**Issue by trabby** [ploneintranet/ploneintranet.theme#40]
The box to select the workflow for the message isn't still implemented in plone.
![bildschirmfoto 2014-11-01 um 13 57 58](https://cloud.githubusercontent.com/assets/454313/4871775/8134801a-61c7-11e4-9bb8-240b2e37a541.png)

**Comment by fulv** [comment]
@gyst could you please comment on this?  I'm not sure whether it belongs in ploneintranet.theme, or whether it has been already tackled somewhere else.

**Comment by gyst** [comment]
This is not a design issue, so I'm closing it here.

It's a low priority user story whoch has not been scheduled for implementation yet.
