### ISSUE TITLE
Search not working in tooltips on prototype

### ISSUE THREAD

**Issue by adrianwhite** [ploneintranet/ploneintranet.theme#72]
**To replicate**
1. Go to: http://demo.ploneintranet.net/dashboard.html
2. Start a comment/post
3. Click on mention or tag icon
4. Type something in the search box

**What happens**
Nothing

**What should happen**
The list of tags/users should be reduced/filtered

![screen shot 2015-02-04 at 09 40 30](https://cloud.githubusercontent.com/assets/1485452/6038086/f75868ae-ac51-11e4-8560-bb93dae14bd8.png)

**Comment by tax** [comment]
@adrianwhite this does works in the live site by making a call to the server which then returns the filtered list.

**Comment by adrianwhite** [comment]
the call works but id for the target for pat-tooltip is not unique. 
If you try: http://demo.ploneintranet.net/open-market-committee/
Use the search in the side-bar and then the search in the mentions tooltip on a comment box.
The search results from the mentions gets injected into the side-bar

**Comment by adrianwhite** [comment]
I'm not sure if this is an issue with pat-tooltip or I am just doing something that is just not supported.

I am trying to do is to generate a tooltip using the content from an area of the page.

Pat-tooltip clones the content (in this case the item-selector include for users or tags) and displays that in the tooltip, leaving the cloned content in place in the page. This means that when a search is performed pat-inject is matching the original element on the page and not the cloned one in the tooltip.

**Comment by adrianwhite** [comment]
FYI I thought this was originally because I had source: ajax in data-pat-tooltip left over from the old way that this was being implemented, but the outcome is the same.

**Comment by adrianwhite** [comment]
I have raised an issue in patterns lib about the cause of this: 
https://github.com/Patternslib/Patterns/issues/394

**Comment by fulv** [comment]
Please see my comments in Patternslib/Patterns#394

**Comment by adrianwhite** [comment]
Cheers @fulv, I'll take a look at the option you mention of using the class on pat-tooltip.

**Comment by adrianwhite** [comment]
will be fixed with merge of #86

**Comment by fulv** [comment]
@adrianwhite   #85/#95 are closed/merged, so this should be complete, right?

**Comment by adrianwhite** [comment]
Yes, I thought waffle would have closed this issue as the pull request and issue were linked in waffle.
