### ISSUE TITLE
Extension for Injection modal

### ISSUE THREAD

**Issue by cornae** [ploneintranet/ploneintranet.theme#76]
Described at: https://github.com/Patternslib/Patterns/issues/389

**Comment by fulv** [comment]
Started work on this branch:
https://github.com/Patternslib/Patterns/tree/inject-with-formaction

**Comment by fulv** [comment]
@cornae, I tried it with the prototype and it works!  You just need to put an **html** in the filename in `formaction="/feedback/banner-notifications.html#documents-cut`.
As soon as this is merged, you'll be able to see it, too.

**Comment by cornae** [comment]
You mean that paths without .html in it wouldn't work?

**Comment by fulv** [comment]
No, they would work.  It's just that in the current prototype `/feedback/banner-notifications.html` is a valid path, `/feedback/banner-notifications` is not.

**Comment by cornae** [comment]
Ok clear :)

**Comment by fulv** [comment]
done and merged.  it works in the prototype, if you add `.html` to the cut and copy buttons.  the delete and rename buttons don't need it.
