### ISSUE TITLE
#context-title does not exist for pat-inject when browsing tree

### ISSUE THREAD

**Issue by adrianwhite** [ploneintranet/ploneintranet.theme#86]
1) Go to: http://127.0.0.1:4000/open-market-committee
2) Click on a folder in the side bar
3) JS error occurs:  ```patterns.pat.inject: No source elements for selector: #context-title```

After merging #85 this will become ```patterns.pat.inject: No source elements for selector: #selector-context-title```

I think this came in with the changes in item-selector.html in 266c241 and subsequently 65e6f1b. It removes an item with an id that is later used in the same template https://github.com/ploneintranet/ploneintranet.theme/blob/master/prototype/_includes/item-selector.html#L238-242
```
<a href="{{ doc.url }}#items" class="follow pat-inject"
                                data-pat-inject="source: #items; target: #items &&
                                source: #selector-contextual-functions; target: #{{ include.id }}-contextual-functions &&
                                source: #context-title; target: #context-title"
                                >
```
This breaks: ```source: #context-title; target: #context-title"```

@cornae is this part of this pat-inject therefore no longer required?

**Comment by fulv** [comment]
@cornae, please reassign to me once you have provided the requested feedback

**Comment by cornae** [comment]
I indeed removed the context title since we were hiding it with CSS and didn't need it anymore. It was a bit of technical depth in the code. Apparently an injection was targeting that. This part of the inject statement can indeed go for type="docs".
