### ISSUE TITLE
Can the stream items have ids?

### ISSUE THREAD

**Issue by pysailor** [ploneintranet/ploneintranet.theme#92]
Hi @cornae,
I would like to have ids on the individual `<div class='post item'>` items in the activity stream of the dashboard and the workspace.
Reason: when a reply is posted, we get back that status element rendered with its new content (=new reply). Using pat-inject, we want to replace the old  `<div class='post item'>` with the current one. Without a unique id, I don't know how to find & replace the correct div.

**Comment by cornae** [comment]
I have no problem with an ID on the items, but it's not necessary. The comment streams already have ID similar to "comment-trail-mypost_1". Is there any specific reason you're diverging from the way the comment injection is proposed in the prototype?

**Comment by pysailor** [comment]
Cornelis G. A. Kolbach wrote on 18/02/15 15:56:
>
> I have no problem with an ID on the items, but it's not necessary. The
> comment streams already have ID similar to "comment-trail-mypost_1".
> Is there any specific reason you're diverging from the way the comment
> injection is proposed in the prototype?
>
Thanks, maybe I'm diverging because not only is the prototype quite
complex enough already and hard to grasp, but the backend code of
plonesocial is in such a state that replication the proto usage patterns
is not an option ATM. A dedicated sprint to clean up plonesocial is needed.

So close this issue for now, until the backend code has been reworked.

**Comment by cornae** [comment]
> Op 18 feb. 2015, om 16:04 heeft Wolfgang Thomas <notifications@github.com> het volgende geschreven:
> 
> Cornelis G. A. Kolbach wrote on 18/02/15 15:56:
> >
> > I have no problem with an ID on the items, but it's not necessary. The
> > comment streams already have ID similar to "comment-trail-mypost_1".
> > Is there any specific reason you're diverging from the way the comment
> > injection is proposed in the prototype?
> >
> Thanks, maybe I'm diverging because not only is the prototype quite
> complex enough already and hard to grasp, but the backend code of
> plonesocial is in such a state that replication the proto usage patterns
> is not an option ATM. A dedicated sprint to clean up plonesocial is needed.
> 
> So close this issue for now, until the backend code has been reworked.

That would be a pity, I put a lot of work in the injections in proto to make it as simple as possible for dev, also considering a lot of other current and future issue on the roadmap, such as maximising the amount of displayed item. Would it help if I led you through the code. So far no developer on the team has ever asked me to explain something about the prototype specification and its markup except Alexander on a few other items…

**Comment by pysailor** [comment]
Thx for adding the ids (3e46919)! 
A tour through the proto would indeed be much appreciated by several devs, e.g. during the sprint in Munich

**Comment by cornae** [comment]
Much looking forward to that.
