### ISSUE TITLE
Injection for tags and mentions use two different ways of supplying target/source

### ISSUE THREAD

**Issue by adrianwhite** [ploneintranet/ploneintranet.theme#94]
I think we should use just one way to avoid confusion. @cornae, which do you think is better:

https://github.com/ploneintranet/ploneintranet.theme/blob/master/prototype/feedback/panel-tags.html#L8
```
action="/feedback/update-social-tags-feedback.html#selected-tags" inject=""
```
https://github.com/ploneintranet/ploneintranet.theme/blob/master/prototype/feedback/panel-mentions.html#L8
```
action="/feedback/update-social-mentions-feedback.html" inject="target: #selected-users; source: #selected-users" 
```

**Comment by cornae** [comment]
I use the short one always when possible and the long one when the short one doesn't listen or when I have multiple targets. But that's personal pref. One is not better then the other, they're different ;).
