### ISSUE TITLE
pat-pickadate needs to be renamed

### ISSUE THREAD

**Issue by jcbrand** [ploneintranet/ploneintranet.theme#97]
The *pat-pickadate* pattern has the same name as an existing Mockup pattern.

Initially I wanted to make it a backward compatible, drop-in replacement for that pattern. This however doesn't look like such a good idea anymore.

There are a few reasons to change the name:

* To distinguish this pattern from the Mockup one
* To allow both patterns to be used in the same site without name clashes.
* The pattern name doesn't follow patternslib conventions

I'm thinking of pat-date or pat-date-picker. @cornae Do you have a suggestion?

CC: @fulv

**Comment by cornae** [comment]
I would say pat-date-picker. It's just a polyfill on `<input type="date" />` isn't it?

**Comment by cornae** [comment]
Another question: How do we handle progressive enhancement with date pickers?  Does native have preference over the .js based version? Like Chrome Desktop and Mobile, Safari Mobile and a few more browsers have native date pickers.

**Comment by jcbrand** [comment]
Currently there is no strategy for progressive enhancement. Pickadate is used for all browsers. If we want to use it only as a polyfill for older browsers, I guess we'll need to add a dependency on modernizr and use that to determine whether Pickadate should be applied or not.

**Comment by jcbrand** [comment]
@cornae I've now renamed pat-pickadate to pat-date-picker.

To test it out, you can clone: https://github.com/Patternslib/pat-date-picker.git
and then run ``make designerhappy``.

I've also made a new release for ploneintranet, so it should be available for you in the PI prototype.
